services:
  logging:
    image: docker.io/library/ubuntu@sha256:d1e2e92c075e5ca139d51a140fff46f84315c0fdce203eab2807c7e495eff4f9
    volumes:
      - ./key.pub:/var/logging/logging.pub:ro
      - ./bin/:/var/logging/bin/:ro
    command: bash /var/logging/bin/example.sh